### ISSUE TITLE
Add Alexa ranks to the `site_visits` table

### ISSUE THREAD

**Issue by gunesacar** [citp/openwpm-data-release#7]
Read site ranks from the `top-1m.csv` files and add as a new column to the `site_visits` table.

**Comment by englehardt** [comment]
For crawls that don't have a `site_visits` table (prior to May 2016): create one, and add in the site rank mapped to `top_url`. In those crawls `top_url` was used as the key. We could also remove the `top_url` column from those tables and replace it with a new `visit_id` so the schema matches the newer databases. (This is only possible because there should be no duplicate `top_url` keys in the databases)

**Comment by gunesacar** [comment]
We first [add the site_visits table](https://github.com/citp/openwpm-data-release/blob/8723da57ae5a6b0a6c56e444d188249d383af187/normalize_db.py#L29) if it is missing, and then [add corresponding the Alexa ranks](https://github.com/citp/openwpm-data-release/blob/8723da57ae5a6b0a6c56e444d188249d383af187/normalize_db.py#L56)
